import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

class Solution {
    public List<Integer> findSubstring(String s, String[] words) {
            List<Integer> result = new ArrayList<>();
                    if (s == null || s.length() == 0 || words == null || words.length == 0) {
                                return result;
                                        }

                                                int wordLen = words[0].length();
                                                        int numWords = words.length;
                                                                int totalLen = wordLen * numWords;

                                                                        if (s.length() < totalLen) {
                                                                                    return result;
                                                                                            }

                                                                                                    // Frequency map for expected words
                                                                                                            Map<String, Integer> wordCount = new HashMap<>();
                                                                                                                    for (String word : words) {
                                                                                                                                wordCount.put(word, wordCount.getOrDefault(word, 0) + 1);
                                                                                                                                        }

                                                                                                                                                // Run sliding window for each possible word-length offset
                                                                                                                                                        for (int i = 0; i < wordLen; i++) {
                                                                                                                                                                    int left = i;
                                                                                                                                                                                int right = i;
                                                                                                                                                                                            Map<String, Integer> currentCount = new HashMap<>();
                                                                                                                                                                                                        int count = 0; // Number of valid words currently in the window

                                                                                                                                                                                                                    while (right + wordLen <= s.length()) {
                                                                                                                                                                                                                                    String word = s.substring(right, right + wordLen);
                                                                                                                                                                                                                                                    right += wordLen;

                                                                                                                                                                                                                                                                    if (wordCount.containsKey(word)) {
                                                                                                                                                                                                                                                                                        currentCount.put(word, currentCount.getOrDefault(word, 0) + 1);
                                                                                                                                                                                                                                                                                                            count++;

                                                                                                                                                                                                                                                                                                                                // If word frequency exceeds target, shrink window from left
                                                                                                                                                                                                                                                                                                                                                    while (currentCount.get(word) > wordCount.get(word)) {
                                                                                                                                                                                                                                                                                                                                                                            String leftWord = s.substring(left, left + wordLen);
                                                                                                                                                                                                                                                                                                                                                                                                    currentCount.put(leftWord, currentCount.get(leftWord) - 1);
                                                                                                                                                                                                                                                                                                                                                                                                                            count--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    left += wordLen;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Found a valid concatenated substring
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (count == numWords) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        result.add(left);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Invalid word: reset window and clear current counts
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    currentCount.clear();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        count = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            left = right;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }