import java.util.*;

class Solution {
    public List<String> fullJustify(String[] words, int maxWidth) {
            List<String> result = new ArrayList<>();
                    int i = 0;
                            int n = words.length;

                                    while (i < n) {
                                                int j = i + 1;
                                                            int lineLength = words[i].length();

                                                                        // Find how many words fit in the current line
                                                                                    while (j < n && lineLength + 1 + words[j].length() <= maxWidth) {
                                                                                                    lineLength += 1 + words[j].length();
                                                                                                                    j++;
                                                                                                                                }

                                                                                                                                            int numOfWords = j - i;
                                                                                                                                                        StringBuilder sb = new StringBuilder();

                                                                                                                                                                    // Case 1: Last line or single word in the line -> Left-justified
                                                                                                                                                                                if (j == n || numOfWords == 1) {
                                                                                                                                                                                                for (int k = i; k < j; k++) {
                                                                                                                                                                                                                    sb.append(words[k]);
                                                                                                                                                                                                                                        if (k < j - 1) sb.append(" ");
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                        while (sb.length() < maxWidth) {
                                                                                                                                                                                                                                                                                            sb.append(" ");
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                        // Case 2: Fully justified line
                                                                                                                                                                                                                                                                                                                                                        int totalCharLength = 0;
                                                                                                                                                                                                                                                                                                                                                                        for (int k = i; k < j; k++) {
                                                                                                                                                                                                                                                                                                                                                                                            totalCharLength += words[k].length();
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                            int totalSpaces = maxWidth - totalCharLength;
                                                                                                                                                                                                                                                                                                                                                                                                                                            int spacesBetweenWords = totalSpaces / (numOfWords - 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            int extraSpaces = totalSpaces % (numOfWords - 1);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int k = i; k < j; k++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sb.append(words[k]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (k < j - 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int spacesToApply = spacesBetweenWords + (k - i < extraSpaces ? 1 : 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (int s = 0; s < spacesToApply; s++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sb.append(" ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    result.add(sb.toString());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                i = j; // Move to the next set of words
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }